config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  resources :events
  resources :users, only: %i[show new create index]
  get 'login' => 'users#login'
  get 'logout' => 'users#logout'
  get 'signup' => 'users#new'
  post 'signup' => 'user#create'
  post 'login' => 'users#auth'
  post 'attend' => 'events#attend'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendence.rb
class Attendence < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, foreign_key: 'creator_id', class_name: 'User'
  has_many :attendences
  has_many :attendees, through: :attendences, source: :user

  scope :past, -> { where('event_date < ?', Time.now).to_a }
  scope :upcoming, -> { where('event_date > ?', Time.now).to_a }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, foreign_key: :creator_id
  has_many :attendences
  has_many :attended_events, through: :attendences, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    @previous = Event.past
    @upcomming = Event.upcoming
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
    @attendees = @event.attendees.to_a
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  # def edit
  # end

  # Post / attend
  def attend
    current_user = User.find_by(id: session[:current_user_id])
    @event = Event.find(params[:id])
    @event.attendees << current_user
    redirect_to user_path(current_user)
  end

  # POST /events
  # POST /events.json
  def create
    current_user = User.find_by(id: session[:current_user_id])
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  # def update
  #   respond_to do |format|
  #     if @event.update(event_params)
  #       format.html { redirect_to @event, notice: 'Event was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @event }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @event.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /events/1
  # DELETE /events/1.json
  # def destroy
  #   @event.destroy
  #   respond_to do |format|
  #     format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:title, :description, :event_date, :location)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @events = Event.where(creator_id: @user.id).all
    @past_events = @events.past
    @future_events = @events.upcoming
    @previous_events = @user.attended_events.past
    @upcomming_events = @user.attended_events.upcoming
  end

  # ex GET /users/new
  # Get /signup
  def new
    @user = User.new
  end

  # ex POST /users
  # post /signup
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:current_user_id] = @user.id
        session[:current_username] = @user.username
        session[:current_user_fullname] = @user.full_name
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def login
    @user = User.new
  end

  def logout
    session.destroy
    redirect_to events_path
  end

  def auth
    @user = User.find_by(username: params[:username])

    if @user.nil?
      flash[:notice] = 'username not Valid'
      redirect_to login_path
    else
      session[:current_user_id] = @user.id
      session[:current_username] = @user.username
      session[:current_user_fullname] = @user.full_name
      flash[:notice] = 'User Logged in'
      redirect_to user_path(@user)
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:full_name, :username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_loggedin?
    !session[:current_user_id].nil?
  end

  def current_user
    User.find(session[:current_user_id]) if user_loggedin?
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def already_subscribe?
    attendees = @event.attendees
    current_user = User.where(id: session[:current_user_id])
    attendees.include?(current_user[0])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :event_date %>
    <%= form.datetime_select :event_date %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Event date</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.description %></td>
        <td><%= event.event_date %></td>
        <td><%= event.location %></td>
        <td><%= link_to 'Show', event %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h3>Previous events</h3>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Event date</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @previous.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.description %></td>
        <td><%= event.event_date %></td>
        <td><%= event.location %></td>
        <td><%= link_to 'Show', event %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h3>Upcomming events</h3>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Event date</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @upcomming.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.description %></td>
        <td><%= event.event_date %></td>
        <td><%= event.location %></td>
        <td><%= link_to 'Show', event %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Created by:</strong>
  <%= @event.creator.full_name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Event date:</strong>
  <%= @event.event_date %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<h3> Event Attendees are : </h3>
<ul>
 <% @attendees.each do |attendee| %>
    <li> <%= attendee.full_name %></li>
  <% end %>
</ul>

<% if !already_subscribe? %>
  <%= link_to 'Click to attend Event', {:controller => "events", :action => "attend", :id => @event.id,}, method: :post %>
<% else %>
  <h3> You already subscribed to this event! </h3>
<% end %>


<br>
<br>
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>PrivateEvents</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

  <% if user_loggedin? %>
    <small><%= link_to 'Create Event', new_event_path %></small> |
  <% end %> 
  <small><%= link_to 'Events list', events_path %></small> |
  <small><%= link_to 'Users list', users_path %></small><br><br>

  <% if !user_loggedin? %>
    <%= link_to 'login', login_path %>
    <%= link_to 'Signup', signup_path %>
  <% else %>
    <%= link_to current_user.full_name, user_path(current_user) %>
    <%= link_to 'log out', logout_path %>
  <% end %>

  <%= yield %>

</body>


</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :full_name %>
    <%= form.text_field :full_name %>
  </div>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_login_form.html.erb
<%= form_with url: '/login' do |form| %>
  <% if flash[:notice] %>
    <div id="error_explanation">
      <h2><%= notice %></h2>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="actions">

    <%= form.submit 'Sign in' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Full name</th>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.full_name %></td>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/login.html.erb
<h1>Login</h1>

<%= render 'login_form', user: @user %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Full name:</strong>
  <%= @user.full_name %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<h3> List of the past events created by: <%= @user.username %> </h3>
<ul>
  <% @past_events.each do |eve| %>
    <li> Title: <%= eve.title %> Location: <%= eve.location %> </li>
  <% end %>
</ul>

<h3> List of the upcomming events created by: <%= @user.username %> </h3>
<ul>
  <% @future_events.each do |eve| %>
    <li> Title: <%= eve.title %> Location: <%= eve.location %> </li>
  <% end %>
</ul>
<br><br>

<h2> List of the previous events attended by <%= @user.username %> : </h2>
<ul>
  <% @previous_events.each do |event| %>
         <li>Title: <%= event.title %> Location: <%= event.location %> Date: <%= event.event_date %></li>
  <% end %>
</ul>

<h2> List of the previous events that <%= @user.username %> will attend : </h2>

<ul>
  <% @upcomming_events.each do |event| %>
     <li>Title: <%= event.title %> Location: <%= event.location %> Date: <%= event.event_date %></li>
  <% end %>
</ul>